set_false_path -from [get_clocks clk1] -to [get_clocks clk3]
set_false_path -from [get_clocks clk3] -to [get_clocks clk1]
set_false_path -from [get_clocks clk2] -to [get_clocks clk3]
set_false_path -from [get_clocks clk3] -to [get_clocks clk2]
set_false_path -from [get_clocks clk1] -to [get_clocks clk2]
set_false_path -from [get_clocks clk2] -to [get_clocks clk1]